<a href="https://colab.research.google.com/github/binghin2/Pytorch_basic/blob/main/Matrix_basic2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
a = torch.tensor([1,2,3,4,5,6,7,8,9])
print(a[0])
print(a[1])
print(a[-1]) # 맨 마지막
print(a[1:4]) # 1부터 3번째까지
print(a[7:]) # 7부터 끝까지
print(a[:7]) # 7까지
print(a[:])
# [a:b] 란 a부터b까지 없으면 그냥 none임

tensor(1)
tensor(2)
tensor(9)
tensor([2, 3, 4])
tensor([8, 9])
tensor([1, 2, 3, 4, 5, 6, 7])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [ ]:
A = torch.tensor([[1,2,3], [4,5,6], [7,8,9]]) #리스트 속 리스트
print("1:",A[0]) # A의 첫번째 뭉텅이
print("2:",A[-1])
print("3:",A[1:])
print("4:",A[:])
print("5:",A[0][2])
print("6:",A[0,2])

1: tensor([1, 2, 3])
2: tensor([7, 8, 9])
3: tensor([[4, 5, 6],
        [7, 8, 9]])
4: tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
5: tensor(3)
6: tensor(3)


In [ ]:
B = [[1,2,3,4], [5,6,7,8]]
print("1:",B)
print("2:",B[0][2])
print("3:",A[1,:])
print("4:",A[1,0:3:2]) # 0부터 3미만까지 2간격 -> 1행 0열, 1행 2열
print("5:",A[:][2])
print("6:", A[:,2])

1: [[1, 2, 3, 4], [5, 6, 7, 8]]
2: 3
3: tensor([4, 5, 6])
4: tensor([4, 6])
5: tensor([7, 8, 9])
6: tensor([3, 6, 9])


In [ ]:
# 3 dimension matrix

A = torch.tensor([[[0,1,2,3], [4,5,6,7], [8,9,10,11]],  # 3행4열
 [[12,13,14,15], [16,17,18,19], [20,21,22,23]]])        # 3행4열
print(A)
print(A.shape) # shape 값은 Size(몇개, 행, 열)
print(A[0,1,2])


a = torch.tensor([[1,2,3,4]]) # b와 비교하여 대괄호가 하나 늘었는데, shape size는 차원이 하나 생김
b = torch.tensor([1,2,3,4])
print(a.shape)
print(b.shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
torch.Size([2, 3, 4])
tensor(6)
torch.Size([1, 4])
torch.Size([4])
