<a href="https://colab.research.google.com/github/binghin2/Pytorch_basic/blob/main/Matrix_basic2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [ ]:
a = torch.tensor([1,2,3,4,5,6,7,8,9])
print(a[0])
print(a[1])
print(a[-1]) # 맨 마지막
print(a[1:4]) # 1부터 3번째까지
print(a[7:]) # 7부터 끝까지
print(a[:7]) # 7까지
print(a[:])
# [a:b] 란 a부터b까지 없으면 그냥 none임

tensor(1)
tensor(2)
tensor(9)
tensor([2, 3, 4])
tensor([8, 9])
tensor([1, 2, 3, 4, 5, 6, 7])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [ ]:
A = torch.tensor([[1,2,3], [4,5,6], [7,8,9]]) #리스트 속 리스트
print("1:",A[0]) # A의 첫번째 뭉텅이
print("2:",A[-1])
print("3:",A[1:])
print("4:",A[:])
print("5:",A[0][2])
print("6:",A[0,2])

1: tensor([1, 2, 3])
2: tensor([7, 8, 9])
3: tensor([[4, 5, 6],
        [7, 8, 9]])
4: tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
5: tensor(3)
6: tensor(3)


In [ ]:
B = [[1,2,3,4], [5,6,7,8]]
print("1:",B)
print("2:",B[0][2])
print("3:",A[1,:])
print("4:",A[1,0:3:2]) # 0부터 3미만까지 2간격 -> 1행 0열, 1행 2열
print("5:",A[:][2])
print("6:", A[:,2])

1: [[1, 2, 3, 4], [5, 6, 7, 8]]
2: 3
3: tensor([4, 5, 6])
4: tensor([4, 6])
5: tensor([7, 8, 9])
6: tensor([3, 6, 9])


In [ ]:
# 3 dimension matrix

A = torch.tensor([[[0,1,2,3], [4,5,6,7], [8,9,10,11]],  # 3행4열
 [[12,13,14,15], [16,17,18,19], [20,21,22,23]]])        # 3행4열
print(A)
print(A.shape) # shape 값은 Size(몇개, 행, 열)
print(A[0,1,2])


a = torch.tensor([[1,2,3,4]]) # b와 비교하여 대괄호가 하나 늘었는데, shape size는 차원이 하나 생김
b = torch.tensor([1,2,3,4])
print(a.shape)
print(b.shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
torch.Size([2, 3, 4])
tensor(6)
torch.Size([1, 4])
torch.Size([4])


In [ ]:
print(A)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


In [ ]:
A[[0,1,1,0],[0,1,2,1],[3,3,2,1]]
# 0번째, 0행,3열 = 3
# 1번째 1행 3열 = 19
# 1번째 2행 2열 = 22
# 0번째 1행 1열 = 5

tensor([ 3, 19, 22,  5])

In [ ]:
# boolean indexing
a = [1,2,3,4,5,3,3]
print("1.",a==3)  # a 가 int 3이랑 같냐?
A = torch.tensor([[1,2,3,4], [5,3,7,3]])
print("2.",A>3) # tensor 들 중에서 index 값이 3보다 큰걸 찾아서
print("3.",A[A>3]) # 변수 뒤에 대괄호가 열리면 그 앞 변수에대해서 indexing 을 하겠다는 의미
# 3번은 A 에대해서 indexing 하는거임 bool 타입의 matrix로
# A 는 2행4열임
# A[A>3] 은 A 중 True인 값을가지고 index으로 내보
A[A>3] = 100 # 이건 3보다 큰값을 100으로 바꾼거 == Masking
print("4.",A)

A = torch.tensor([[1,2], [3,4], [5,6], [7,8]])
B = torch.tensor([True, False, False, True])
print(A)
print("5.",A[B,:])
# A를 B값을 토대로 indexing 하겠음 B는 0행, 3행만 True
b = torch.tensor([1,2,3,4])
print("6.",b[ [True, True, False, False]])
c = [1,2,3,4]

1. False
2. tensor([[False, False, False,  True],
        [ True, False,  True, False]])
3. tensor([4, 5, 7])
4. tensor([[  1,   2,   3, 100],
        [100,   3, 100,   3]])
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
5. tensor([[1, 2],
        [7, 8]])
6. tensor([1, 2])


In [ ]:
# tensor 로 indexing
a = torch.tensor([1,2,3,4,5])
A=a[2]
print("1.",A)
A = a[torch.tensor(2)]
print("2.",A)
A = a[torch.tensor([2,3,4])] # 2,3,4 번째 tensor를 가져옴
print("3.",A)
A = a[torch.tensor([[2,2,2], [3,3,3]])] # 2번째 tensor, 3번째 tensor로 2행3열만듬
print("4.",A)

a = torch.tensor([[1,2,3], [4,5,6]])
print("5.",a[torch.tensor(0)])
A = a[torch.tensor([[0,1],[1,1]])]
# 앞에 [0,1] << 여기의 0은 a[0] = [1,2,3] 이거고 1은 a[1] = [4,5,6] 임 그러므로 [0,1] = [1,2,3], [4,5,6]
# [1,1] 역시 [4,5,6], [4,5,6]
print("6.",A.shape) # '2'차원'2'행'3'열
print("7.",A) # segmentation 결과를 보여줄때 사용함! 이게 뭐냐면 그림을 indexing 할라고 사용한대

1. tensor(3)
2. tensor(3)
3. tensor([3, 4, 5])
4. tensor([[3, 3, 3],
        [4, 4, 4]])
5. tensor([1, 2, 3])
6. torch.Size([2, 2, 3])
7. tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[4, 5, 6],
         [4, 5, 6]]])


In [3]:
a = torch.tensor([[1,2,3], [4,5,6]])
A = a[torch.tensor([[0,1], [1,1]])]
# 이걸 list형태로 indexing 하려면
# A 의 값은 [1,2,3], [4,5,6],
# [4,5,6], [4,5,6]
# shape 는 2차원 2행 3열임 이걸 list 형태로 하려면? 개노가다임
print(A)
A = torch.tensor([[[0,1,2,3], [4,5,6,7], [8,9,10,11]],[[12,13,14,15], [16,17,18,19], [20,21,22,23]]])
print(A)
A[[0,1,1,0], [0,1,2,1], [3,3,2,1]] # A[0,0,3]

tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[4, 5, 6],
         [4, 5, 6]]])
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


tensor([ 3, 19, 22,  5])