<a href="https://colab.research.google.com/github/binghin2/Pytorch_basic/blob/main/Matrix_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# numpy와 닮은 pytorch

In [7]:
import torch
a = torch.tensor([1,2,3,4])
print(a)
print(type(a))
print(a.dtype)
print(a.shape) # a의 크기

b = torch.tensor([1,2,3.1,4])
print(b)
print(b.dtype) # 하나라도 실수면 실수 type
print(b.shape)

tensor([1, 2, 3, 4])
<class 'torch.Tensor'>
torch.int64
torch.Size([4])
tensor([1.0000, 2.0000, 3.1000, 4.0000])
torch.float32
torch.Size([4])


In [10]:
c = torch.tensor([[1,2,3], [3,4,5]])
# torch.tensor([[1,2], [1,2,3]]) 같은 방식은 정의가 안됨. matrix 이기 때문
print(c)
print(c.shape) # 2행3열
print(c.ndim) # dimension의 수
print(c.numel()) # number of element 총 성분의 개수

tensor([[1, 2, 3],
        [3, 4, 5]])
torch.Size([2, 3])
2
6


In [19]:
print(torch.zeros(5)) # 5개의 0행렬
print(torch.zeros_like(c)) # c와 같은 영행렬
print(torch.ones(5)) # 5개 1행렬
print(torch.zeros(3,3)) # 3x3 의 영행렬
print(torch.arange(3,10,2)) # 3부터 10까지 2씩 증가
print(torch.arange(0,1,0.1)) # 소수점도 가능
print(torch.linspace(0,1,10)) # 0 에서 1을 포함한 10개


tensor([0., 0., 0., 0., 0.])
tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([1., 1., 1., 1., 1.])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([3, 5, 7, 9])
tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000])
tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])


In [21]:
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])
c = a + b
print(c)

tensor([5, 7, 9])


In [23]:
c = a * b
print(c)

tensor([ 4, 10, 18])


In [29]:
A = torch.tensor([[1,2,3], [1,2,3]])
B = torch.tensor([[4,5,6], [1,2,3]])
C = A + B
D = A - B
print(C)
print(D)
print(A*B) # 성분끼리의 곱
print(A/B)
print(B**2)

tensor([[5, 7, 9],
        [2, 4, 6]])
tensor([[-3, -3, -3],
        [ 0,  0,  0]])
tensor([[ 4, 10, 18],
        [ 1,  4,  9]])
tensor([[0.2500, 0.4000, 0.5000],
        [1.0000, 1.0000, 1.0000]])
tensor([[16, 25, 36],
        [ 1,  4,  9]])


In [33]:
A = torch.tensor([[1,2,], [3,4]])
B = torch.tensor([[1,2], [3,4]])
print(A)
print(B)
print(A@B)

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]])
tensor([[ 7, 10],
        [15, 22]])
