<a href="https://colab.research.google.com/github/binghin2/Pytorch_basic/blob/main/torch_function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
A = torch.randn(3,3) # Normal 의 n => Gaussian. 평균0 분산1 default
B = torch.rand(3,3) # 이건 uniform 0~1값
print(A)
print(B)

tensor([[ 0.5045,  0.4159,  2.3099],
        [ 0.6743,  0.0065, -0.8714],
        [ 0.1320, -0.7415,  0.8183]])
tensor([[0.9700, 0.2739, 0.0666],
        [0.9586, 0.7218, 0.5956],
        [0.8692, 0.4066, 0.4262]])


In [5]:
A = torch.randn(3,3)
## torch 함수 속 변수는 반드시 tensor 형태여야만 함
print('1. ',A)
print('2. ',torch.abs(A)) # 절댓값
print('3. ',torch.sqrt(torch.abs(A))) # square root
print('4. ',torch.exp(A)) # e^A
print('5. ',torch.log(torch.abs(A)))
print('6. ',torch.log(torch.exp(torch.tensor(1))))
print('7. ',torch.log10(torch.tensor(10)))
print('8. ',torch.log2(torch.tensor(2)))
print('9. ',torch.round(A)) #반올림
print('10. ',torch.round(A,decimals=2)) # 소수점 둘째자리까지
print('11. ',torch.floor(A)) # 내림
print('12. ',torch.ceil(A)) # 올림


1.  tensor([[ 0.5484, -2.1628, -0.2395],
        [-0.6869, -0.3395,  0.5382],
        [-0.7833,  0.4981,  1.3321]])
2.  tensor([[0.5484, 2.1628, 0.2395],
        [0.6869, 0.3395, 0.5382],
        [0.7833, 0.4981, 1.3321]])
3.  tensor([[0.7405, 1.4706, 0.4894],
        [0.8288, 0.5827, 0.7336],
        [0.8850, 0.7057, 1.1542]])
4.  tensor([[1.7305, 0.1150, 0.7870],
        [0.5031, 0.7121, 1.7130],
        [0.4569, 1.6455, 3.7891]])
5.  tensor([[-0.6008,  0.7714, -1.4292],
        [-0.3755, -1.0802, -0.6195],
        [-0.2442, -0.6970,  0.2868]])
6.  tensor(1.0000)
7.  tensor(1.)
8.  tensor(1.)
9.  tensor([[ 1., -2., -0.],
        [-1., -0.,  1.],
        [-1.,  0.,  1.]])
10.  tensor([[ 0.5500, -2.1600, -0.2400],
        [-0.6900, -0.3400,  0.5400],
        [-0.7800,  0.5000,  1.3300]])
11.  tensor([[ 0., -3., -1.],
        [-1., -1.,  0.],
        [-1.,  0.,  1.]])
12.  tensor([[ 1., -2., -0.],
        [-0., -0.,  1.],
        [-0.,  1.,  2.]])


In [6]:
print(torch.sin(torch.tensor(torch.pi/6)))
print(torch.cos(torch.tensor(torch.pi/3)))
print(torch.tan(torch.tensor(torch.pi/4)))
print(torch.tanh(torch.tensor(-10)))

type(torch.tensor(1)/6)

tensor(0.5000)
tensor(0.5000)
tensor(1.)
tensor(-1.)


torch.Tensor

In [7]:
# Boolean
torch.nan # not a number
print(torch.log(torch.tensor(-1)))
print(torch.isnan(torch.tensor([1,2,torch.nan,3,4])))
print(torch.isinf(torch.tensor([1,2,3,4,torch.inf])))
# 결과창에 nan이 나왔을때 문제가 발생한 거임
# 그걸 체크해 볼 수 있는 함수

tensor(nan)
tensor([False, False,  True, False, False])
tensor([False, False, False, False,  True])


In [8]:
print("hello")

hello


In [11]:
!nvidia-smi

Tue Dec  2 06:11:30 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   36C    P8             11W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [18]:
x = torch.tensor([1.], requires_grad=True)
print(x)
print(x.requires_grad)

tensor([1.], requires_grad=True)
True


In [ ]:
x = torch.tensor([1.]) # 1. = 1임
print(x)
print(x.requires_grad)

x.requires_grad_(True)
print(x)
print(x.requires_grad)

tensor([1.])
False
tensor([1.], requires_grad=True)
True


In [ ]:
x = torch.tensor([1.], requires_grad=True)
y = x**2           # y = x^2
print(y)
print(x.grad)
y.backward()       # dy/dx = 2*x = 2 미분함수임 requires_grad=True 일때만 미분가능
print(x.grad)      # tensor([2.]) y = x^2 일때 x=1일때 미분값은 2 dy/dx = 2*x
print(x)

tensor([1.], grad_fn=<PowBackward0>)
None
tensor([2.])
