<a href="https://colab.research.google.com/github/binghin2/Pytorch_basic/blob/main/torch_function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [23]:
A = torch.randn(3,3) # Normal 의 n => Gaussian. 평균0 분산1 default
B = torch.rand(3,3) # 이건 uniform 0~1값
print(A)
print(B)

tensor([[-0.6888, -0.0104, -0.3466],
        [ 1.1545,  0.4805,  0.6813],
        [-0.8352,  1.2769, -0.9142]])
tensor([[0.1917, 0.4808, 0.9437],
        [0.2761, 0.6732, 0.9734],
        [0.8966, 0.7749, 0.1980]])


In [25]:
A = torch.randn(3,3)
## torch 함수 속 변수는 반드시 tensor 형태여야만 함
print('1. ',A)
print('2. ',torch.abs(A)) # 절댓값
print('3. ',torch.sqrt(torch.abs(A))) # square root
print('4. ',torch.exp(A)) # e^A
print('5. ',torch.log(torch.abs(A)))
print('6. ',torch.log(torch.exp(torch.tensor(1))))
print('7. ',torch.log10(torch.tensor(10)))
print('8. ',torch.log2(torch.tensor(2)))
print('9. ',torch.round(A)) #반올림
print('10. ',torch.round(A,decimals=2)) # 소수점 둘째자리까지
print('11. ',torch.floor(A)) # 내림
print('12. ',torch.ceil(A)) # 올림


1.  tensor([[-0.9785,  0.2012,  0.7230],
        [-0.3906,  1.3230,  0.0210],
        [-1.2977,  0.1258,  1.1838]])
2.  tensor([[0.9785, 0.2012, 0.7230],
        [0.3906, 1.3230, 0.0210],
        [1.2977, 0.1258, 1.1838]])
3.  tensor([[0.9892, 0.4486, 0.8503],
        [0.6250, 1.1502, 0.1449],
        [1.1392, 0.3546, 1.0880]])
4.  tensor([[0.3759, 1.2229, 2.0606],
        [0.6767, 3.7546, 1.0212],
        [0.2732, 1.1340, 3.2668]])
5.  tensor([[-0.0218, -1.6035, -0.3243],
        [-0.9402,  0.2799, -3.8631],
        [ 0.2606, -2.0735,  0.1687]])
6.  tensor(1.)
7.  tensor(1.)
8.  tensor(1.)
9.  tensor([[-1.,  0.,  1.],
        [-0.,  1.,  0.],
        [-1.,  0.,  1.]])
10.  tensor([[-0.9800,  0.2000,  0.7200],
        [-0.3900,  1.3200,  0.0200],
        [-1.3000,  0.1300,  1.1800]])
11.  tensor([[-1.,  0.,  0.],
        [-1.,  1.,  0.],
        [-2.,  0.,  1.]])
12.  tensor([[-0.,  1.,  1.],
        [-0.,  2.,  1.],
        [-1.,  1.,  2.]])


In [26]:
print(torch.sin(torch.tensor(torch.pi/6)))
print(torch.cos(torch.tensor(torch.pi/3)))
print(torch.tan(torch.tensor(torch.pi/4)))
print(torch.tanh(torch.tensor(-10)))

type(torch.tensor(1)/6)

tensor(0.5000)
tensor(0.5000)
tensor(1.)
tensor(-1.)


torch.Tensor

In [27]:
# Boolean
torch.nan # not a number
print(torch.log(torch.tensor(-1)))
print(torch.isnan(torch.tensor([1,2,torch.nan,3,4])))
print(torch.isinf(torch.tensor([1,2,3,4,torch.inf])))
# 결과창에 nan이 나왔을때 문제가 발생한 거임
# 그걸 체크해 볼 수 있는 함수

tensor(nan)
tensor([False, False,  True, False, False])
tensor([False, False, False, False,  True])


In [ ]:
A